// class Hii{
 
//     public static void main(String[] args)
//     {
//         System.out.println("hello world");
//     }
//  }
// class Hii {
  
//     public static void main(String[] args)
//     {
//         System.out.println("Helloworld");
//     }
// }
import java.util.*;
class Hii{
    public static void main (String[] args){

        // System.out.println("helloworld");
        int a=2;
        int b=3;
        int sum=a+b;
        System.out.println(sum);
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the value of x");
        int x = sc.nextInt();
        System.out.println(x);



    }
}